package com.oze.entity;

import java.time.LocalDate;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import org.hibernate.annotations.Type;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
@JsonIgnoreProperties({"hibernateLazyInitializer"})
@Entity
public class Staff {
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Long id;
	private String name;
	
	@Column(unique=true)
	@Type(type="org.hibernate.type.UUIDCharType")    //This should be autogenerated
	private UUID uuid = UUID.randomUUID();
	
	private LocalDate registrationDate;
	
	public Staff() {}
	public Staff(Long id, String name, UUID uuid, LocalDate registrationDate) {
		this.id = id;
		this.name = name;
		this.uuid = uuid;
		this.registrationDate = registrationDate;
	}
	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public UUID getUuid() {
		return uuid;
	}
	public void setUuid(UUID uuid) {
		this.uuid = uuid;
	}
	public LocalDate getRegistrationDate() {
		return registrationDate;
	}
	public void setRegistrationDate(LocalDate registrationDate) {
		this.registrationDate = registrationDate;
	}
	@Override
	public String toString() {
		return "Staff [id=" + id + ", name=" + name + ", uuid=" + uuid + ", registrationDate=" + registrationDate + "]";
	}
	
	
	
}
